### ISSUE TITLE
MVP List 

### ISSUE THREAD

**Issue by PLUCS2** [sam-lilly/root_directory#1]
- [x] Specify which features the user must be logged in to use 
- [x] Shopping Cart MVP will take you only 1 day (unless you add map to that MVP allowing for delivery information to be accepted) - specify what you'd like to do  
- [x] Specify the Product listing includes the `show` and `index` pages 
- [x] Include the contact us section of the website as the last MVP feature 

Excellent work!

**Comment by samantha-lilly** [comment]
Edited- thanks!

*Specified which features user must be logged in to do.
*Added map for checkout and added a contact section.
