### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by PLUCS2** [sam-lilly/root_directory#2]
- [x] Users do not have a username 
- [x] The Address book feature has the option to add a company name and a phone number - the Address table should reflect that 
- [x] The plants table, planters table, etc. and the products table both hold a price (which one will actually hold the price of the item? it should only be in one place) 
- [x] What is `type` on the Planters table? 
- [x] How will you indicate that the order has been placed? 
- [x] How will you account for requests to the contact us section? 

Nice job! Let me know if you have any questions

**Comment by samantha-lilly** [comment]
*Adjusted users table to remove username
*Added company and phone number to address table
*Adjusted plants, planters, and accessories table to remove price, price will live on the products table
*Removed type from planters table as there was only one active category listed on site for type
*Added a column 'purchased' to cart table as boolean showing if cart has been checked out
*Added a contacts table for requests to the contact us section

Thanks!
