### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by PLUCS2** [sam-lilly/root_directory#3]
- [x] Will you ever have more than 1 user in your state? 
- [x] Side note: I LOVE Asheville, NC :) 
- [x] What is `plantDbId`? (On the Greenery site) 
- [x] Will you ever have more than 1 user's cart loaded in your frontend state? 
- [x] Will you ever have contacts in your frontend state? If yes, what are they for? Who sees that information? 

Excellent work! Let me know if you have any questions!

**Comment by samantha-lilly** [comment]
*No,  there will only be one user in my state at a time, unless this means when two people are logged in at once from separate computers?
*Yessss, Asheville is great, (that is my best friends info (haha)), I lived for a really long time before moving here :)
*plantDbId is the ID of each specific plant for the 'plant care database', where users can click to see the plant care instructions. each kind of plant has their own and there are a few different listings for each plant.
*No, there will not be more than 1 users cart loaded in front end state, as each user will only ever have 1 cart.
*No, there will not be contacts in front end of state. Contacts are sent to the back through the form and will not be interacted with on the frontend.


-I do have a few questions about having more than 1 user or more than 1 users cart, I do not think I would have more than one at a time but am unsure of what it would look like if there were to be multiple people logged in at once from different computers.
