### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by PLUCS2** [sam-lilly/root_directory#4]
## Backend 
- [x] `GET /api/addresses/new - form to add a new address` - you will not need a route for this on the backend as the form itself will be rendered on the frontend with react. Same with `GET /api/addresses/:id/edit - form to edit existing address` 
- [x] You will not need a route that returns all products since you can only view products by category 
- [x] You need an index page for carts if you can see previous order details - but it should send up products in that specific cart or order - as well as current cart. This is taken care of by your orders route

## Frontend 
- [x] Please specify your routes not just your components 
- You will need a separate frontend route for every "page" that you can navigate to. 
- [x] Your components look good! 

Let me know if you have any questions!

**Comment by samantha-lilly** [comment]
*Edited
*Removed routes from backend
*Added routes for each "page" on the front end

Thanks :)
